application: ozbonds
version: 1
runtime: go
api_version: go1

handlers:
  - url: /
    secure: always
    static_files: index.html
    upload: index.html

  - url: /js/ozbonds.js
    secure: always
    static_files: js/ozbonds.js
    upload: js/ozbonds.js

  - url: /css/bootstrap.min.css
    secure: always
    static_files: css/bootstrap.min.css
    upload: css/bootstrap.min.css

  - url: /ladderDetails.handlebars
    secure: always
    mime_type: application/javascript
    static_files: ladderDetails.handlebars
    upload: ladderDetails.handlebars

  - url: /(.+)
    secure: always
    script: _go_app
